default_language_version:
  python: python3
exclude: >
  (?x)^(
      deluge/ui/web/docs/template/.*|
      deluge/tests/data/.*svg|
      deluge/ui/web/.*\.css|
      deluge/ui/web/js/.*\.js|
      deluge/ui/web/js/extjs/ext-.*\.js|
      deluge/ui/web/docs/|
      deluge/ui/web/themes/images/|
      .*\.py*|
      .*\.html|
      .*\.md|
      \.github/workflows/.*|
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      - id: ruff
        name: Chk Ruff
        args: [--fix]
      - id: ruff-format
        name: Fmt Ruff
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        name: Fmt Prettier
        # Workaround to list modified files only.
        args: [--list-different]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: Fix End-of-files
        exclude_types: [javascript, css]
      - id: mixed-line-ending
        name: Fix Line endings
        args: [--fix=auto]
      - id: trailing-whitespace
        name: Fix Trailing whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        stages: [manual]
