[build-system]
requires = ["setuptools>=64", "setuptools-git-versioning"]
build-backend="setuptools.build_meta"

[project]
name="deluge"
description='Deluge BitTorrent Client'
authors= [
{name = 'Deluge Team'}
]
maintainers= [
	{name = 'Calum Lind', email='calumlind+deluge@gmail.com'}
]
keywords= [
	"torrent",
	"bittorrent",
	"p2p",
	"fileshare",
	"filesharing"
]

classifiers=[
	'Development Status :: 4 - Beta',
	'Environment :: Console',
	'Environment :: Web Environment',
	'Environment :: X11 Applications :: GTK',
	'Framework :: Twisted',
	'Intended Audience :: End Users/Desktop',
	'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
	'Programming Language :: Python',
	'Operating System :: MacOS :: MacOS X',
	'Operating System :: Microsoft :: Windows',
	'Operating System :: POSIX',
	'Topic :: Internet'
]
requires-python='>=3.7'
license={file = 'LICENSE' }
dynamic = ["version", "readme", "dependencies", "entry-points", "scripts", "gui-scripts"]

[project.urls]
Homepage='https://deluge-torrent.org'
Sourcecode='http://git.deluge-torrent.org/deluge'
'GitHub (mirror)'='https://github.com/deluge-torrent/deluge'
Issues='https://dev.deluge-torrent.org/report/1'
Discussion='https://forum.deluge-torrent.org'
Documentation='https://deluge.readthedocs.io'

[tool.setuptools.packages.find]
where=["."]
exclude = ["deluge.tests*", "deluge.plugins.*", "build*"]

[tool.setuptools]
include-package-data=false

[tool.setuptools.package-data]
deluge = [
    'ui/data/pixmaps/*.png',
    'ui/data/pixmaps/*.svg',
    'ui/data/pixmaps/*.ico',
    'ui/data/pixmaps/*.gif',
    'ui/data/pixmaps/flags/*.png',
    'plugins/*.egg',
    'i18n/*/LC_MESSAGES/*.mo'
    ]
"deluge.ui.web" = [
    'index.html',
    'css/*.css',
    'icons/*.png',
    'images/*.gif',
    'images/*.png',
    'js/*.js',
    'js/extjs/*.js',
    'render/*.html',
    'themes/css/*.css',
    'themes/images/*/*.gif',
    'themes/images/*/*.png',
    'themes/images/*/*/*.gif',
    'themes/images/*/*/*.png'
    ]
"deluge.ui.gtk3" = ['glade/*.ui']

[tool.setuptools.exclude-package-data]
"*" = ["build*"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
ci = {file = ["requirements-tests.txt", "requirements-ci.txt"]}
dev = {file = ["docs/requirements.txt", "requirements-tests.txt"]}
docs = {file = ["docs/requirements.txt"]}
tests = {file = ["requirements-tests.txt"]}

[tool.setuptools-git-versioning]
enabled = true
version_callback="version:get_version"

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# Dump tracebacks if a test takes longer than X seconds
faulthandler_timeout = 60
# Hide logged warnings and errors in test output.
log_cli_level = "CRITICAL"
addopts = "--basetemp=_pytest_temp"
markers = [
    "todo: Tests that are yet to be written",
    "gtkui: Tests for GTK code",
    "security: Security related tests",
    "slow: Tests that are particularly slow",
    "internet: Tests that require internet connectivity",
]
filterwarnings = [
    "ignore::DeprecationWarning:gi",
    "ignore::DeprecationWarning:twisted.internet.gireactor",
    "ignore:twisted.web.resource.*:DeprecationWarning",
    "ignore:Using readBody.*:DeprecationWarning",
    "ignore:resume_data is deprecated.*:DeprecationWarning:deluge.core.alertmanager",
]

[tool.ruff]
line-length = 88
builtins = ["_", "_n", "__request__"]
extend-exclude = ["dist", "build"]
target-version = "py37"

[tool.ruff.format]
# Prefer single quotes over double quotes
quote-style = "single"

[tool.ruff.lint]
ignore = [
    "N818", # error-suffix-on-exception-name
    "E501", # Line-too-long, let formatter resolve it

]
select = [
    "A", # flake8-builtins
    "E", # pycodestyle
    "F", # Pyflakes
    "N", # pep8-naming
    "W", # pycodestyle
    "INT", # flake8-gettext
    "I", # isort

]

[tool.ruff.lint.flake8-gettext]
extend-function-names = ["_n"]

[tool.ruff.lint.extend-per-file-ignores]
# E402 import not top of file (gi version check required before import)
"deluge/**/gtkui/*.py" = ["E402"]
"deluge/**/gtkui.py" = ["E402"]
"deluge/plugins/Stats/deluge_stats/graph.py" = ["E402"]
"deluge/ui/gtk3/*.py" = ["E402"]

[tool.pyright]
reportMissingImports = "information"
reportMissingModuleSource = "information"
